In [19]:
import numpy as np
from scipy import linalg
import matplotlib.pyplot as plt
from sympy import init_printing
from scipy import linalg as sci_linalg
import sympy

## 1. Matrix Representation of a System of Linear Equations

A linear system is a collection of equations involving the same variables. It can be represented as a coefficient matrix $A$ and a constant vector $\bar{b}$.

In [17]:
# System from Slide 7:
# 2x1 + 3x2 + x3 = 3;
# 7x2 - 4x3 = 10;
# x3 = 1
# NumPy/SciPy (Numerical)
A_num = np.array([[2, 3, 1], [0, 7, -4], [0, 0, 1]])
b_num = np.array([3, 10, 1])

# SymPy (Symbolic - preserves exact integers)
A_sym = sympy.Matrix([[2, 3, 1], [0, 7, -4], [0, 0, 1]])
b_sym = sympy.Matrix([3, 10, 1])

A_sym

Matrix([
[2, 3,  1],
[0, 7, -4],
[0, 0,  1]])

## 2. Solving a System of Linear Equations

Solving finding the values ($s_1, \dots, s_n$) that satisfy all equations in the system.

In [20]:
# NumPy/SciPy Numerical Solution
x_num = sci_linalg.solve(A_num, b_num)

# SymPy Symbolic Solution (gives exact fractions if necessary)
x_sym = A_sym.LUsolve(b_sym)

print(f"Numerical Solution: {x_num}")
print(f"Symbolic Solution: {x_sym}")

Numerical Solution: [-2.  2.  1.]
Symbolic Solution: Matrix([[-2], [2], [1]])


## 3. Augmented and Coefficient Matrix

The coefficient matrix consists of only the coefficients of the variables, while the augmented matrix includes the constants column ($b$) separated (often visually) by a vertical line.

In [22]:
# NumPy
augmented_num = np.column_stack((A_num, b_num))

# SymPy (row_join appends columns horizontally)
augmented_sym = A_sym.row_join(b_sym)

augmented_sym

Matrix([
[2, 3,  1,  3],
[0, 7, -4, 10],
[0, 0,  1,  1]])

## 4. Size of a Matrix

The size of a matrix is defined by the number of its rows ($m$) and columns ($n$), expressed as $m \times n$.

In [23]:
# NumPy
rows_num, cols_num = A_num.shape

# SymPy
rows_sym, cols_sym = A_sym.shape # Returns (rows, cols)

print(f"Size: {rows_sym} rows by {cols_sym} columns")

Size: 3 rows by 3 columns


## 5. Adding a Row and a Column to a Matrix

Modifying a matrix by adding new observations (rows) or new features (columns).

In [27]:
# NumPy
A_new_row = np.vstack([A_num, [1, 1, 1]])

# SymPy
A_new_row_sym = A_sym.row_insert(3, sympy.Matrix([[1, 1, 1]]))
A_new_col_sym = A_sym.col_insert(3, sympy.Matrix([5, 5, 5]))

A_new_col_sym

Matrix([
[2, 3,  1, 5],
[0, 7, -4, 5],
[0, 0,  1, 5]])

In [28]:
A_new_row_sym

Matrix([
[2, 3,  1],
[0, 7, -4],
[0, 0,  1],
[1, 1,  1]])

## 6. Reading One Row or One Column from a Matrix

Accessing specific data points or features within the matrix.

In [30]:
# NumPy
row_0 = A_num[0, :]
col_1 = A_num[:, 1]

# SymPy
row_0_sym = A_sym.row(0)
col_1_sym = A_sym.col(1)

col_1_sym

Matrix([
[3],
[7],
[0]])

## 7. Echelon Form (EF) and RREF

Echelon Form requires zero rows at the bottom and leading entries to move right in each subsequent row . Reduced Row Echelon Form (RREF) further requires leading entries to be 1 and be the only non-zero entry in their column.

In [40]:
A_num = np.array([[2, 3, 1], [0, 7, -4], [0, 0, 1]])
A_sym = sympy.Matrix([[2, 3, 1], [0, 7, -4], [0, 0, 1]])

# SciPy (Numerical Echelon Form via LU decomposition)
P, L, U = sci_linalg.lu(A_num) # U is in Echelon Form

# SymPy (Direct RREF - The most fitting tool for this concept)
rref_matrix, pivot_indices = A_sym.rref()

rref_matrix

Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

In [41]:
P, L, U

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[ 2.,  3.,  1.],
        [ 0.,  7., -4.],
        [ 0.,  0.,  1.]]))

## 8. Pivot Columns and Free Variables

Pivot positions are leading 1s in RREF. Non-pivot columns represent free variables.

In [42]:
# SymPy's rref() explicitly returns the pivot indices
print(f"Pivot Column Indices: {pivot_indices}")

Pivot Column Indices: (0, 1, 2)


## 9. Vectors

Vectors represent movement from the origin and are often represented as $n \times 1$ matrices.

In [47]:
# NumPy
v_num = np.array([1, 2])

# SymPy
v_sym = sympy.Matrix([1, 2])

v_sym

Matrix([
[1],
[2]])

## 10. Matrix Constructed from Column Vectors

A matrix can be viewed as a set of column vectors.

In [49]:
v1, v2 = np.array([1, 2]), np.array([1, -1])

# NumPy
A_from_v = np.column_stack((v1, v2))

# SymPy
A_from_v_sym = sympy.Matrix.hstack(sympy.Matrix(v1), sympy.Matrix(v2))

A_from_v_sym

Matrix([
[1,  1],
[2, -1]])

## 11. Vector Addition and Scalar Multiplication

Operations are performed entry-by-entry.

In [54]:
u, v = np.array([1, 2]), np.array([3, 4])
c = 10

# NumPy/SymPy both use standard operators
u + v, c*u

(array([4, 6]), array([10, 20]))

In [56]:
# SymPy Example
u_s, v_s = sympy.Matrix([1, 2]), sympy.Matrix([3, 4])

u_s + v_s

Matrix([
[4],
[6]])

## 12. Linear Combinations

The sum of scaled vectors $c_1\bar{v}_1 + \dots + c_p\bar{v}_p$.

In [58]:
v1_s, v2_s = sympy.Matrix([1, 2]), sympy.Matrix([1, -1])
# Example from Slide 22: 2*v1 + 3*v2
y_s = 2*v1_s + 3*v2_s

y_s

Matrix([
[5],
[1]])

## 13. Matrix Equation $A\bar{x} = \bar{b}$

The matrix-vector product $A\bar{x}$ is a linear combination of the columns of $A$.

In [59]:
x_s = sympy.Matrix([1, 2, 3])
# Ax = b
b_s = A_sym * x_s

b_s

Matrix([
[11],
[ 2],
[ 3]])

## 14. Matrix-Vector Multiplication (Row-Vector Rule)

The $i$-th entry of $A\bar{x}$ is the dot product of row $i$ and $\bar{x}$.

In [63]:
# NumPy
res_num = A_num @ b_num # '@' is the matrix product operator

# SymPy
res_sym = A_sym * b_sym # '*' is matrix multiplication in SymPy

res_sym

Matrix([
[37],
[66],
[ 1]])

## 15. Linear Independence

A set is independent if the only solution to the vector equation is the trivial solution.

In [64]:
# NumPy (Check rank)
is_indep_num = np.linalg.matrix_rank(A_num) == A_num.shape[1]

# SymPy (Check nullspace; if only 0 is there, it's independent)
nullspace = A_sym.nullspace()
is_indep_sym = len(nullspace) == 0

print(f"Linearly Independent: {is_indep_sym}")

Linearly Independent: True


## 16. Norms ($L_1, L_2$)

Norms measure the length/distance of a vector.

In [65]:
v_vec = np.array([3, 4])

# NumPy
l2_num = np.linalg.norm(v_vec, ord=2)

# SymPy
v_s_vec = sympy.Matrix([3, 4])
l2_sym = v_s_vec.norm(2)

print(f"L2 Norm: {l2_sym}")

L2 Norm: 5


## 17. Inner Product (Dot Product)

Measures similarity between vectors.

In [66]:
# NumPy
dot_num = np.dot(b_num, b_num)

# SymPy
dot_sym = b_sym.dot(b_sym)

print(f"Inner Product: {dot_sym}")

Inner Product: 110


## 18. Matrix Addition and Subtraction

Requires same-sized matrices; operations are entry-by-entry.

In [68]:
B_s = sympy.Matrix([[2, -1], [3, 1]])
C_s = sympy.Matrix([[2, 4], [0, -1]])

B_s + C_s

Matrix([
[4, 3],
[3, 0]])

## 19. Matrix Scaling

Multiplying every entry by a scalar.

In [70]:
S = 5
S * B_s

Matrix([
[10, -5],
[15,  5]])

## 20. Matrix Multiplication

Defined if columns of the first match rows of the second.

In [72]:
A_m = np.array([[1, 2], [2, 3], [3, 4]])
B_m = np.array([[2, -1], [3, 1]])

# NumPy
res_m_num = A_m @ B_m

# SymPy
res_m_sym = sympy.Matrix(A_m) * sympy.Matrix(B_m)

res_m_sym

Matrix([
[ 8, 1],
[13, 1],
[18, 1]])

## 21. Transpose

Columns are formed from the rows of $A$.

In [73]:
# NumPy
A_t_num = A_num.T

# SymPy
A_t_sym = A_sym.T

A_t_sym

Matrix([
[2,  0, 0],
[3,  7, 0],
[1, -4, 1]])

## 22. Matrix Inverse

A square matrix $A$ is invertible if $A^{-1}A = I$. If $A$ is invertible, $A\bar{x}=\bar{b}$ has a unique solution.

In [75]:
# NumPy
A_inv_num = np.linalg.inv(A_num)

# SymPy
A_inv_sym = A_sym.inv()

A_inv_sym

Matrix([
[1/2, -3/14, -19/14],
[  0,   1/7,    4/7],
[  0,     0,      1]])

## 23. Eigenvalues and Eigenvectors

Defined by $A\bar{x} = \lambda\bar{x}$.

In [84]:
# NumPy (Numerical approximation)
vals_num, vecs_num = np.linalg.eig(A_num)

# SymPy (Exact analytical solution)
# Returns {val: multiplicity}
eig_vals = A_sym.eigenvals()
# Returns [(val, mult, [vecs])]
eig_vecs = A_sym.eigenvects()

eig_vals

{1: 1, 7: 1, 2: 1}

## 24. Singular Value Decomposition (SVD)

Factorization $A = U\Sigma V^T$ used for dimensionality reduction.

In [88]:
# NumPy/SciPy (Standard for SVD)
U, S, Vt = np.linalg.svd(A_m)

# SymPy (Can compute singular values exactly)
sing_vals = sympy.Matrix(A_m).singular_values()

print("Numerical Singular Values:", S)

Numerical Singular Values: [6.54675564 0.37415323]


In [89]:
sing_vals

[sqrt(5*sqrt(73)/2 + 43/2), sqrt(43/2 - 5*sqrt(73)/2)]

In [91]:
sing_vals[0].evalf()  # Numerical approximation of the first singular value

6.54675563644267